version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    environment:
      - AUTH_SECRET=1mfpwwdm0J8rqEvTV4QJacl4WF7XtGTMca15YX3MkGU=
      - URL_BASE=http://98.85.18.206:8082/api-clean
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://98.85.18.206:8083/