version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:443"
    environment:
      - AUTH_SECRET=${AUTH_SECRET:1mfpwwdm0J8rqEvTV4QJacl4WF7XtGTMca15YX3MkGU=}
      - URL_BASE=https:integradora.duckdns.org:8082/apí-clean